name: hr_attendance
description: "Attendance app for office."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  envied:
  supabase_flutter:
  google_fonts:
  figma_squircle_updated:
  animated_custom_dropdown:
  shared_preferences:
  flutter_riverpod:
  riverpod_annotation:
  toastification:
  page_transition:
  url_launcher:
  internet_connection_checker_plus:
  loading_animation_widget:
  material_dialogs:
  iconly:
  flashy_tab_bar2:
  cached_network_image:
  shimmer:
  fluttertoast:
  easy_date_timeline:
  slide_action:
  app_links:
  date_picker_timeline:
  intl:
  glass:
  geolocator:
  detect_fake_location:
  flutter_map:
  latlong2:
  syncfusion_flutter_datepicker:
  image_picker:
  image:
  device_info_plus:
  jailbreak_root_detection:
  # app_clone_checker: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator:
  build_runner:
  riverpod_generator:
  flutter_launcher_icons:
  rename_app:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
